### Voici a quoi ressemblent les données après les deux premieres etapes de la pipeline

routers = [{'hostname': '111:R1',
            'interfaces':
                [{'ipv6_addresses':['2001::1/64'],
                'ipv6_enable': True,
                'name': 'GigabitEthernet0/0',
                'rip_enable': False}],
                'loopback':{'ipv6': '2001:1:1:1::1'},
                'ospf':{'router_id': 'R1'},
                bgp:{as: '111', address :{ipv6:'2001:1:1:1::1'} }}
 {'hostname': '111:R2',
  'interfaces': [{'ipv6_addresses': ['2002::2/64'],
                  'ipv6_enable': True,
                  'name': 'GigabitEthernet0/0',
                  'rip_enable': False}],
  'loopback': {'ipv6': '2001:1:1:1::2'},
  'ospf': {'router_id': 'R2'}},
 {'hostname': '112:R3',
  'interfaces': [{'ipv6_addresses': ['2001::3/64'],
                  'ipv6_enable': True,
                  'name': 'GigabitEthernet0/0',
                  'rip_enable': True}],
  'loopback': {'ipv6': '2001:1:1:2::1'}},
 {'hostname': '112:R4',
  'interfaces': [{'ipv6_addresses': ['2002::4/64'],
                  'ipv6_enable': True,
                  'name': 'GigabitEthernet0/0',
                  'rip_enable': True}],
  'loopback': {'ipv6': '2001:1:1:2::2'}}]